# /etc/nginx/conf.d/default.conf
server {
  listen 80;

  # Nginx가 파일을 찾을 기본 경로
  root /usr/share/nginx/html;

  # 기본으로 제공할 파일
  index index.html;

  # 모든 요청에 대해
  location / {
    # 먼저 요청된 URI와 일치하는 파일이 있는지 찾아보고,
    # 없으면 디렉토리가 있는지 찾아보고,
    # 둘 다 없으면 /index.html을 반환합니다. (SPA의 핵심!)
    try_files $uri $uri/ /index.html;
  }
}