# /learn_fornt_end_project/manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  # 이 Deployment를 방금 만든 프론트엔드 네임스페이스에 위치시킵니다.
  namespace: llm-app-frontend
spec:
  # 안정적인 서비스를 위해 프론트엔드 파드는 2개로 시작하겠습니다.
  # Nginx는 매우 가벼워서 리소스를 거의 차지하지 않습니다.
  replicas: 2

  selector:
    # 이 Deployment가 관리할 파드의 꼬리표(Label)
    matchLabels:
      app: frontend

  template:
    metadata:
      # 생성될 파드에 붙여줄 꼬리표
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          
          # 프론트엔드용 Dockerfile로 빌드된 이미지를 사용합니다.
          # 마찬가지로 지금은 임시 경로를 사용합니다.
          image: 49.50.132.167/llm-project/frontend:latest

          # Nginx가 80번 포트에서 실행되므로, 컨테이너의 80번 포트를 개방합니다.
          ports:
            - containerPort: 80